"""empty message

Revision ID: 86804f7dc5f9
Revises: c9eb5d2b75f6
Create Date: 2022-01-22 22:56:53.377308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86804f7dc5f9'
down_revision = 'c9eb5d2b75f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
